sudo: false
language: android
jdk:
- oraclejdk8

git:
  depth: false

branches:
  only:
    - master

install:
- yes | sdkmanager --verbose "build-tools;28.0.3"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-28"
- yes | sdkmanager --verbose "extras;android;m2repository"

# Check tools and dependencies installed
- yes | sdkmanager --list

before_script:
- ./signing/decrypt.sh

script:
# force init of adb way before any Gradle task that uses ADB; prevents a timeout error that skips emulators of android-24
- adb devices
- ./gradlew build

env:
  global:
  - secure: h4Y7ZvgbvOj5T71ubRcw3Fy3KXF8qHugRFLGK3q2R9YuRsDAf8XH+Y/UiXyH8sac2QSj7Zlny1kA1DEJgwhTXs9wsAVKVJCQNTJGEvhm/4uQgPeNMzMv07Lqe8V+KUBsFH5qhfPJO357ERW0k2f2qljoLSHtHStclt7iGvFdynA=
  - secure: o9L6lXWpXowhQSdiUSmajliBUkQ6n7NrBUqhC09lqe7yXSGhEsgGRXqHoT3q2B4uIqGSiLCa9HQbW0dfDQCs+pADmzHIl3zbTViR88TSaIhOiTrqMUUl5iaO++pneZ2TzgU9bbGHbl6Ixjc6iALH2+F7P+RUM6vLTNPcfnCJa3g=
  - secure: ydxZrS7+1ht3p1tC6DE9W9bjLQGjMkwFBwyhNmcdEM6538kN8ZCBQe7NxSsCrC1nSDBLQ17Cziv0XJHl/pCfPrbkrPPgVFpjDfPeqC2zcGcCNcFQUEylXCvQ4uRU2hKL6dPqCsOQ57Pv3qwpPoprl/usoN5Wh8V7BKplU88ZaYM=
  matrix:
  - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a

after_script:
- ./signing/cleanup.sh

deploy:
  provider: releases
  api_key: ${api_key}
  file_glob: true
  file:
  - "app/build/outputs/apk/release/*.apk"
  skip_cleanup: true
  on:
    tags: true

